Branch one
profnitt/profnitt.github.io pull request #14
Opened 2021-01-19 08:56 UTC by Garvit-tyagi

mobile reponsive images done

2021-02-02 11:25 UTC, 9401adarsh commented
Good to go ahead

2021-02-02 11:35 UTC, sidvenu requested changes

2021-02-02 11:35 UTC, sidvenu commented on assets/css/style.css
> +
Not necessary

2021-02-02 11:35 UTC, sidvenu commented on assets/css/style.css
> +  height: auto; */
Not necessary

2021-02-02 11:35 UTC, sidvenu commented on index.html
> +        </div>
Format this properly

2021-02-13 14:28 UTC, shyam-king commented
touching the "events" arrow in the navbar (mobile) itself scrolls to the events section @Garvit-tyagi

2021-02-13 14:35 UTC, shyam-king commented
> touching the "events" arrow in the navbar (mobile) itself scrolls to the events section @Garvit-tyagi

This one @Garvit-tyagi let;s do in another PR. I am merging this PR for now.

2021-02-13 14:36 UTC, merged