navigation bar and title change
profnitt/profnitt.github.io pull request #3
Opened 2020-12-19 17:21 UTC by Garvit-tyagi

2020-12-20 12:48 UTC, sidvenu requested changes

2020-12-20 12:48 UTC, sidvenu commented on index.html
>                  </ul>
The `href`s feel incorrect. Change it according to the content. Later when others work on the sections, they can refer to the navbar and decide the section ID.

2020-12-20 12:48 UTC, sidvenu commented on index.html
> +          <!-- <a href="https://www.youtube.com/watch?v=jDDaplaOz7Q" class="venobox play-btn mb-4" data-vbtype="video" data-autoplay="true"></a> -->
If not needed, remove this line. Don't comment it out.

2020-12-20 12:48 UTC, sidvenu commented on index.html
> +      <h3>ProffNITT</h3>
Not a part of navbar, remove this change.

2020-12-20 12:48 UTC, sidvenu commented on inner-page.html
>        <div class="row justify-content-center">
This page itself is not going to be used by us as of now. Remove all the changes made.

2020-12-20 17:07 UTC, shyam-king requested changes

2020-12-20 17:07 UTC, shyam-king commented on index.html
> +  <title>ProffNITT </title>
typo

2020-12-20 17:07 UTC, shyam-king commented on index.html
> +              <li><a href="#bharatx">BharatX</a></li>
Don't add bharatx in the navbar itself, either put it under some "projects" tab or don't add it at all.

2020-12-20 17:07 UTC, shyam-king commented on index.html
> +          <h1>ProffNITT</h1>
typo

2020-12-20 18:08 UTC, shyam-king commented on index.html
> +          <h1 class="logo"><a href="index.html">ProfNITT</a></h1>
do we need it to be "index.html", can we have it as a tag that scrolls to the top or something? Because, when we click on it, it reloads the page.

2020-12-21 16:09 UTC, shyam-king approved these changes

2020-12-21 16:20 UTC, sidvenu requested changes

2020-12-21 16:20 UTC, sidvenu commented on index.html
> +  <title>ProfNITT </title>
```suggestion
  <title>ProfNITT</title>
```

2020-12-21 16:20 UTC, sidvenu commented on index.html
> +          <h1 class="logo"><a href="#goToTop">ProfNITT</a></h1>
This doesn't work. See how the bottom right button works.

2020-12-21 16:20 UTC, sidvenu commented on index.html
>                <li class="active"><a href="index.html">Home</a></li>
Change `href` to `#` alone.

2020-12-21 16:25 UTC, sidvenu requested changes

2020-12-21 16:25 UTC, sidvenu commented on index.html
> +              <li class="drop-down"><a href="">Events</a>
```suggestion
              <li><a href="#members">Members</a></li>
              <li class="drop-down"><a href="">Events</a>
```

2020-12-21 16:25 UTC, sidvenu commented on index.html
> +                  <li><a href="#guest lectures and webinars">GUEST LECTURES AND WEBINARS</a></li>
```suggestion
                  <li><a href="#investas">INVESTAS</a></li>
                  <li><a href="#insight">INSIGHT</a></li>
                  <li><a href="#talk">THE TALK</a></li>
                  <li><a href="#guest-lectures">GUEST LECTURES AND WEBINARS</a></li>
```

2020-12-21 16:25 UTC, sidvenu commented on index.html
> +                </ul>
```suggestion
                <ul>
                  <li><a href="#bharatx">BharatX</a></li>
                  <li><a href="#navriti">Navriti</a></li>
                </ul>
```

2020-12-21 16:25 UTC, sidvenu commented on index.html
> +
```suggestion
          <h1>ProfNITT</h1>
          <h2>The Finance and Investment club of NIT Trichy.</h2>
```

2020-12-21 16:46 UTC, sidvenu requested changes

2020-12-21 16:46 UTC, sidvenu commented on index.html
> +
```suggestion
```

2020-12-21 16:46 UTC, sidvenu commented on index.html
> +
```suggestion
```

2020-12-21 16:46 UTC, sidvenu commented on index.html
> +  <title>ProfNITT </title>
Bump.

2020-12-21 20:46 UTC, sidvenu requested changes

2020-12-21 20:46 UTC, sidvenu commented on index.html
> +                  <li><a href="#guest-lectures">GUEST LECTURES AND WEBINARS</a></li>
```suggestion
                  <li><a href="#investas">Investas</a></li>
                  <li><a href="#insight">Insight</a></li>
                  <li><a href="#talk">The Talk</a></li>
                  <li><a href="#guest-lectures">Guest Lectures and Webinars</a></li>
```

2020-12-21 20:48 UTC, merged