changed theme, removed unnecessary sections, fixed hyperlinks of navbar
profnitt/profnitt.github.io pull request #6
Opened 2021-01-16 15:56 UTC by Garvit-tyagi

2021-01-16 16:44 UTC, 9401adarsh commented on index.html
>      <!-- ======= Portfolio Section ======= -->
Just Comment it as Members section to get a better clarity

2021-01-16 16:50 UTC, 9401adarsh approved these changes

2021-01-17 05:57 UTC, sidvenu requested changes
1. Remove Inductions and Get Started from navbar
2. Add ProfNITT's official logo to navbar and footer instead of plain text
3. Add ProfNITT's circle logo to Title bar (favicon)

2021-01-18 07:43 UTC, sidvenu requested changes

2021-01-18 07:43 UTC, sidvenu commented on index.html
> +              <!-- <li><a href="#inductions">Inductions</a></li> -->
Remove

2021-01-18 07:43 UTC, sidvenu commented on index.html
> +          <!-- <h1 class="logo"><a href="#">ProfNITT</a></h1> -->
Remove

2021-01-18 07:43 UTC, sidvenu commented on index.html
> +      <!-- <h3>ProfNITT</h3> -->
Remove

2021-01-18 07:44 UTC, 9401adarsh approved these changes

2021-01-18 08:31 UTC, sidvenu approved these changes

2021-01-18 08:31 UTC, merged